### ISSUE TITLE
Limit Number of Player a node/definemod can use

### ISSUE THREAD

**Issue by ChocoboGamer** [XeroOl/notitg-mirin#30]
I think the current way to make node/definemod player specific/limit is odd, 
this is a proposed change that may make it better.

```lua
-- current syntax
definemod{'mod',function(mod,pn)
    if on <= 4 then
        -- code
    end
end}

-- suggested syntax
definemod{'mod',function(mod)
    -- code
end,
plr = {1,2,3,4}}
```

**Comment by XeroOl** [comment]
If the two forms you showed are equivalent, player specific nodes wouldn't be able to output mods.
I think it may be possible to split the node data structure up into 8 separate node data structures, one for each player. That would allow for this sort of syntax to work, even with nodes that have outputs.

**Comment by ChocoboGamer** [comment]
this is not good I am sorry, please go to #51
