### ISSUE TITLE
A way to defer funcs by a number of frames

### ISSUE THREAD

**Issue by XeroOl** [XeroOl/notitg-mirin#43]

**Comment by XeroOl** [comment]
I added `defer=` to funcs,  you can set `defer=true` to delay by a frame, or `defer=n` to delay by n frames

**Comment by XeroOl** [comment]
I still need to do this

**Comment by XeroOl** [comment]
The reason this hasn't happened yet is that it causes there to not be a canonical order to funcs. This messes up a ton of assumptions that are being made in the mirin template backend, so I need to think longer about how to make this work and also stay consistent.

ie, 
```lua
func {0, function() print('a') end}
func {1, function() print('b') end, delay = 1} --
func {60, function() print('c') end}
```
Would print 'abc' if played from front to end, but `acb` if started after beat 60. I have no idea under what circumstances this is desired and under what circumstances it isn't.

**Comment by ChocoboGamer** [comment]
After consideration by Xero, this functionality would conflict with how `func` is currently setup in the template and would cause several sorting issues if implemented.
