### ISSUE TITLE
Back to .lua

### ISSUE THREAD

**Issue by XeroOl** [XeroOl/notitg-mirin#52]
I think .lua is nicer because of editor support and user sanity. I want to switch as many files from .xml to .lua as possible if it doesn't make heysora mad.

**Comment by HeySora** [comment]
.lua files are broken on a ctrl+r, we had to fix some OISRT files using Puuro's SpriteText because of that

it needs a change in game, it's yet another ScreenReadyCommand but (the LUA_PATH is set *after* on a Ctrl+R)

**Comment by XeroOl** [comment]
So if Mirin Template were to temporarily leave ScreenReadyCommand, it would work?

**Comment by HeySora** [comment]
depends on whether LUA_PATH is set correctly in OnCommand but still
(you can check that by printing it, doing a ctrl+R, comparing the output

**Comment by XeroOl** [comment]
From HeySora on discord. Apparently you can reliably load lua files using a pattern like this. I'll have to do some tests to see if GetCurrentSong is accurate from an InitCommand, but this looks like a great place to start.

```lua
local code = loadfile(GAMESTATE:GetRealPath(GAMESTATE:GetCurrentSong():GetSongDir() ..'lua/mods.lua'))
```

**Comment by HeySora** [comment]
it's used in ghost and purple people eater and nobody complained about it
even through taro's additionalfolders and other people using some similar pref

**Comment by XeroOl** [comment]
Currently, everything is just prefixed with `GAMESTATE:GetCurrentSong():GetSongDir()`, which seems to be working very well
