### ISSUE TITLE
luaeffect to tween?

### ISSUE THREAD

**Issue by XeroOl** [XeroOl/notitg-mirin#56]
Apparently this has the potential of allowing things to run a frame earlier? I need to test and also ask @HeySora about this

**Comment by XeroOl** [comment]
Apparently tween doesn't show crash messages?
I think I want to stick to luaeffect if that's the case

**Comment by HeySora** [comment]
fwiw you could use `pcall` to work around the issue

**Comment by XeroOl** [comment]
I want to avoid pcall if possible, but that is a good point
