### ISSUE TITLE
V6 Syntax

### ISSUE THREAD

**Issue by XeroOl** [XeroOl/notitg-mirin#58]
I think something like this would be really nice to support.
```lua
ease(0, 10, outExpo, {invert = 100, bumpy = 100}, {mode = 'end', time = true})
```
1) the signature of this function is actually clear, so error checking will run faster
2) no quotes on mod names
3) it is easier for others to make functions with this api
4) not too much more typing than what's currently there
5) it is much more clear to people who are brand-new to lua that `ease` is a function, not some magic syntax
6) it gives people who are learning lua good examples of what tables are instead of bad examples

I don't think there would be any problem supporting this sort of thing

**Comment by XeroOl** [comment]
The first step to accomplishing this sort of thing would be to split the frontend into a separate file that could be swapped out.

**Comment by ChocoboGamer** [comment]
I did it 🦺

**Comment by ChocoboGamer** [comment]
I didn't do it 🗡️

**Comment by XeroOl** [comment]
New plans, we're not really splitting the frontend into two, but there will be a module you can require that has wrappers over the existing functions

**Comment by XeroOl** [comment]
- [ ] ease
- [ ] add
- [ ] acc
- [ ] set
- [ ] func
- [ ] perframe
- [ ] funcease
- [ ] definemod
- [ ] alias
- [ ] maybe others? ask me to edit this comment if you have more that you want to add
