### ISSUE TITLE
Add delta beat as parameter to perframe

### ISSUE THREAD

**Issue by XeroOl** [XeroOl/notitg-mirin#63]
Add a third parameter to perframes.

```lua
perframe{a, b, function(beat, poptions, dt) end}
```
Delta in beats unless time=true, in which case it is in seconds.

On the first frame the perframe is run, the delta would be measured from the theoretical start time to the actual first frame.

Suggested by ryn.

**Comment by ChocoboGamer** [comment]
Discussed with Ryn.
It was determined that ``actor:geteffectdelta()`` is an acceptable substitute for implementing this into the template,
and there was no benefit to using deltabeat over deltatime.

**Comment by XeroOl** [comment]
it may be good to mention this somewhere in docs
