### ISSUE TITLE
Improve default Layout.xml/mods.lua for proxying

### ISSUE THREAD

**Issue by XeroOl** [XeroOl/notitg-mirin#68]
Ideally, it would be as simple as copying the existing proxies, and it would be clear how to put them in different positions.
Right now, it's multiple steps to create player proxies. It's not clear to a beginner how the default mods.lua code is involved.

Also, we could try to make the answer to everyone's first question, "How do I put the players on top of eachother in the middle of the screen?" more obvious and apparent and guessable.

**Comment by ChocoboGamer** [comment]
There is no setupjudge proxy all proxy code is now explicit and organized in mods.lua
