### ISSUE TITLE
Normalize all function names

### ISSUE THREAD

**Issue by ChocoboGamer** [XeroOl/notitg-mirin#74]
the functions provided by the template have fairly inconsistent capitalization.

ie.
```
get_plr
touch_mod
touch_all_mods
sprite
aft
setupJudgeProxy
backToSongWheel
```
all of these should be switched to either camelCase with no _ or something else.
Same with ``func_ease`` as it's the only mod application function with an _
it should be one word, like ``setdefault`` or ``definemod``.

**Comment by XeroOl** [comment]
if we keep the old ones around depricated I would love to switch all of them! I think we agreed that camelCase was the target

**Comment by ChocoboGamer** [comment]
I would like to suggest that we make function names in the `xero` namespace PascalCase and variables in the `xero` namespace should use camelCase.
