### ISSUE TITLE
Support {start, end} percentages in ease

### ISSUE THREAD

**Issue by ChocoboGamer** [XeroOl/notitg-mirin#93]
ease should support having 2 numbers passed into the percentage values of a mod.

the classic syntax should support:
```
ease{0, 1, {100, 0}, 'movex'}
```
the new syntax should support:
```
ease(0, 1, {movex = {100, 0}})
```

**Comment by XeroOl** [comment]
This was done on the dev branch, but we will need to redo it manually for the master branch

**Comment by ChocoboGamer** [comment]
Added support for this in old style syntax, because of changes this also means the new syntax will also have it, as long as we add the correct parsing for it.
